### ISSUE TITLE
RPC Issues found during testing

### ISSUE THREAD

**Issue by ajoycekyrio** [pip-services3-node/pip-services3-rpc-node#2]
# Overview

I have found some issues with the RPC project from my usage of it.
I have implemented the fixes as individual commits and added it to my existing PR located [here](https://github.com/pip-services3-node/pip-services3-rpc-node/pull/1)

# Issue 1

The container does not log that it opened a rest client, it will log that it was closed though.

Here is a log same for this issue.

**Starting Logs**

> [pipservices-kyrio-demo:INFO:2020-04-06T17:28:14.584Z] Press Control-C to stop the microservice...  
> [pipservices-kyrio-demo:WARN:2020-04-06T17:28:14.594Z] Connection to Prometheus server is not configured: NO_CONNECTION: HTTP connection is not set  
> [pipservices-kyrio-demo:DEBUG:2020-04-06T17:28:14.899Z] Opened REST service at http://0.0.0.0:8080  
> [pipservices-kyrio-demo:INFO:2020-04-06T17:28:14.988Z] Container pipservices-kyrio-demo started.  
> [---:TRACE:2020-04-06T17:28:34.822Z] Executing v1/demo.get method  
> [---:TRACE:2020-04-06T17:28:34.823Z] Calling v1/applicationname_url.get_by_id method  

**Closing Logs**

> [pipservices-kyrio-demo:TRACE:2020-04-06T17:29:53.911Z] Stopping pipservices-kyrio-demo container  
> [pipservices-kyrio-demo:DEBUG:2020-04-06T17:29:53.913Z] Closed REST service at http://0.0.0.0:8080  
> [pipservices-kyrio-demo:DEBUG:2020-04-06T17:29:53.914Z] Closed REST service at http://localhost:8081  
> [pipservices-kyrio-demo:INFO:2020-04-06T17:29:53.915Z] Container pipservices-kyrio-demo stopped  
> [pipservices-kyrio-demo:INFO:2020-04-06T17:29:53.918Z] Goodbye!  

**Fix**

The fix for this issue is to add the line `this._logger.debug(correlationId, "Connected via REST to %s", this._uri);` to the RestClient class in the RPC module.

# Issue 2

The commandable service and client don't seem to be working with correlation id.
There is no correlation id in the logs.

**Example**

> [pipservices-kyrio-demo:INFO:2020-04-06T17:37:47.849Z] Container pipservices-kyrio-demo started.  
> [---:TRACE:2020-04-06T17:37:53.418Z] Executing v1/demo.get method  
> [---:TRACE:2020-04-06T17:37:53.420Z] Calling v1/applicationname_url.get_by_id method

**Fix**

The cause of this issue is in the `CommandableHttpService`
The code `let correlationId = req.params.correlation_id;` does not seem to have any query parameters.
There was a change where restify changed to restify-clients, so it's possible that this changed aswel (I'm new to node stuff so I'm not familiar with this), however a fix for this issue is to use the `query` object

Change the line 

> `let correlationId = req.params.correlation_id;`

To

`let correlationId = req.query.correlation_id;`

# Issue 3

The call counter metrics do not have the correct labels. This is because the target label is missing,
Here is a sample of what is returned from the `/metrics` endpoint

```txt
# TYPE exec_count gauge
exec_count{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 1
# TYPE v1_applicationname_url_get_by_id.call_count gauge
v1_applicationname_url_get_by_id.call_count{source="pipservices-kyrio-demo",instance="ajoyky15u"} 1
# TYPE v1_applicationname_url_get_by_id.call_time_max gauge
v1_applicationname_url_get_by_id.call_time_max{source="pipservices-kyrio-demo",instance="ajoyky15u"} 20
# TYPE v1_applicationname_url_get_by_id.call_time_min gauge
v1_applicationname_url_get_by_id.call_time_min{source="pipservices-kyrio-demo",instance="ajoyky15u"} 20
# TYPE v1_applicationname_url_get_by_id.call_time_average gauge
v1_applicationname_url_get_by_id.call_time_average{source="pipservices-kyrio-demo",instance="ajoyky15u"} 20
# TYPE v1_applicationname_url_get_by_id.call_time_count gauge
v1_applicationname_url_get_by_id.call_time_count{source="pipservices-kyrio-demo",instance="ajoyky15u"} 1
# TYPE exec_time_max gauge
exec_time_max{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 22
# TYPE exec_time_min gauge
exec_time_min{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 22
# TYPE exec_time_average gauge
exec_time_average{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 22
# TYPE exec_time_count gauge
exec_time_count{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 1
```

**Fix**

The type is not set in the `RestClient`.
To get the name of the calling client the following code can be used.

`this.constructor.name || "unknown-target"`

After the fix is applied the `/metrics` endpoint returns

```txt
# TYPE exec_count gauge
exec_count{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 1
# TYPE call_count gauge
call_count{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/applicationname_url",command="get_by_id",target="ApplicationNameHttpClientV1"} 1
# TYPE call_time_max gauge
call_time_max{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/applicationname_url",command="get_by_id",target="ApplicationNameHttpClientV1"} 10
# TYPE call_time_min gauge
call_time_min{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/applicationname_url",command="get_by_id",target="ApplicationNameHttpClientV1"} 10
# TYPE call_time_average gauge
call_time_average{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/applicationname_url",command="get_by_id",target="ApplicationNameHttpClientV1"} 10
# TYPE call_time_count gauge
call_time_count{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/applicationname_url",command="get_by_id",target="ApplicationNameHttpClientV1"} 1
# TYPE exec_time_max gauge
exec_time_max{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 11
# TYPE exec_time_min gauge
exec_time_min{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 11
# TYPE exec_time_average gauge
exec_time_average{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 11
# TYPE exec_time_count gauge
exec_time_count{source="pipservices-kyrio-demo",instance="ajoyky15u",service="v1/demo",command="get"} 1
```

**Comment by Dvoikin** [comment]
@ajoycekyrio thanks for updates! Closing the issue.
